// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spring.domain;

import com.spring.domain.Customer;
import com.spring.domain.Lab;

privileged aspect Lab_Roo_JavaBean {
    
    public Customer Lab.getName() {
        return this.name;
    }
    
    public void Lab.setName(Customer name) {
        this.name = name;
    }
    
}
